# Generated by Django 4.0.5 on 2022-06-28 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        ('carts', '0002_alter_cartitem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='gem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.gem'),
        ),
    ]
