# Generated by Django 4.0.5 on 2022-06-23 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gem_name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('color', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('content', models.TextField(blank=True, verbose_name='Contenu')),
                ('images', models.ImageField(blank=True, null=True, upload_to='products')),
                ('stock', models.IntegerField(default=True)),
                ('is_available', models.BooleanField(default=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('modified_date', models.DateField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variation_category', models.CharField(choices=[('quality', 'quality'), ('carat', 'carat')], max_length=100)),
                ('variation_value', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('gem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.gem')),
            ],
        ),
    ]
